(() => {
  'use strict';
  const records = {
    37:{"hero":"杜遷","nickname":"摸著天","activeName":"摸著天・連環追擊","activeText":"對目標連擊並追擊殘血敵人；施術後自身加速。","passiveName":"摸著天・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"摸著天真傳・杜遷","cooldown":2,"mechanic":"dizha_37_chain_swift","primary":"chain","secondary":"swift","power":0.72,"statusPower":18,"signature":"chain:swift:37","stats":{"speed":0,"crit":0.0,"status":0.0}},
    38:{"hero":"宋萬","nickname":"雲裡金剛","activeName":"雲裡金剛・連環追擊","activeText":"對目標連擊並追擊殘血敵人；保護氣血最低隊友。","passiveName":"雲裡金剛・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"雲裡金剛真傳・宋萬","cooldown":3,"mechanic":"dizha_38_chain_guard","primary":"chain","secondary":"guard","power":0.775,"statusPower":21,"signature":"chain:guard:38","stats":{"speed":1,"crit":0.008,"status":0.01}},
    39:{"hero":"朱貴","nickname":"旱地忽律","activeName":"旱地忽律・連環追擊","activeText":"對目標連擊並追擊殘血敵人；提高下一擊暴擊與命中。","passiveName":"旱地忽律・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"旱地忽律真傳・朱貴","cooldown":4,"mechanic":"dizha_39_chain_insight","primary":"chain","secondary":"insight","power":0.83,"statusPower":24,"signature":"chain:insight:39","stats":{"speed":2,"crit":0.016,"status":0.02}},
    40:{"hero":"朱富","nickname":"笑面虎","activeName":"笑面虎・連環追擊","activeText":"對目標連擊並追擊殘血敵人；擊倒敵人時取得少量銀兩。","passiveName":"笑面虎・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"笑面虎真傳・朱富","cooldown":5,"mechanic":"dizha_40_chain_harvest","primary":"chain","secondary":"harvest","power":0.885,"statusPower":27,"signature":"chain:harvest:40","stats":{"speed":3,"crit":0.024,"status":0.03}},
    41:{"hero":"李雲","nickname":"青眼虎","activeName":"青眼虎・連環追擊","activeText":"對目標連擊並追擊殘血敵人；清除自身一項負面狀態。","passiveName":"青眼虎・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"青眼虎真傳・李雲","cooldown":2,"mechanic":"dizha_41_chain_cleanse","primary":"chain","secondary":"cleanse","power":0.94,"statusPower":30,"signature":"chain:cleanse:41","stats":{"speed":4,"crit":0.032,"status":0.0}},
    42:{"hero":"杜興","nickname":"鬼臉兒","activeName":"鬼臉兒・連環追擊","activeText":"對目標連擊並追擊殘血敵人；有機率縮短技能冷卻。","passiveName":"鬼臉兒・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"鬼臉兒真傳・杜興","cooldown":3,"mechanic":"dizha_42_chain_echo","primary":"chain","secondary":"echo","power":0.995,"statusPower":33,"signature":"chain:echo:42","stats":{"speed":5,"crit":0.0,"status":0.01}},
    43:{"hero":"李應","nickname":"撲天雕","activeName":"撲天雕・震陣護軍","activeText":"震傷全敵並為隊伍建立護盾；施術後自身加速。","passiveName":"撲天雕・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"撲天雕真傳・李應","cooldown":4,"mechanic":"dizha_43_quake_swift","primary":"quake","secondary":"swift","power":1.05,"statusPower":36,"signature":"quake:swift:43","stats":{"speed":0,"crit":0.008,"status":0.02}},
    44:{"hero":"朱仝","nickname":"美髯公","activeName":"美髯公・震陣護軍","activeText":"震傷全敵並為隊伍建立護盾；保護氣血最低隊友。","passiveName":"美髯公・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"美髯公真傳・朱仝","cooldown":5,"mechanic":"dizha_44_quake_guard","primary":"quake","secondary":"guard","power":1.105,"statusPower":39,"signature":"quake:guard:44","stats":{"speed":1,"crit":0.016,"status":0.03}},
    45:{"hero":"雷橫","nickname":"插翅虎","activeName":"插翅虎・震陣護軍","activeText":"震傷全敵並為隊伍建立護盾；提高下一擊暴擊與命中。","passiveName":"插翅虎・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"插翅虎真傳・雷橫","cooldown":2,"mechanic":"dizha_45_quake_insight","primary":"quake","secondary":"insight","power":1.16,"statusPower":18,"signature":"quake:insight:45","stats":{"speed":2,"crit":0.024,"status":0.0}},
    46:{"hero":"穆春","nickname":"小遮攔","activeName":"小遮攔・震陣護軍","activeText":"震傷全敵並為隊伍建立護盾；擊倒敵人時取得少量銀兩。","passiveName":"小遮攔・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"小遮攔真傳・穆春","cooldown":3,"mechanic":"dizha_46_quake_harvest","primary":"quake","secondary":"harvest","power":0.72,"statusPower":21,"signature":"quake:harvest:46","stats":{"speed":3,"crit":0.032,"status":0.01}},
    47:{"hero":"穆弘","nickname":"沒遮攔","activeName":"沒遮攔・震陣護軍","activeText":"震傷全敵並為隊伍建立護盾；清除自身一項負面狀態。","passiveName":"沒遮攔・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"沒遮攔真傳・穆弘","cooldown":4,"mechanic":"dizha_47_quake_cleanse","primary":"quake","secondary":"cleanse","power":0.775,"statusPower":24,"signature":"quake:cleanse:47","stats":{"speed":4,"crit":0.0,"status":0.02}},
    48:{"hero":"薛永","nickname":"病大蟲","activeName":"病大蟲・震陣護軍","activeText":"震傷全敵並為隊伍建立護盾；有機率縮短技能冷卻。","passiveName":"病大蟲・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"病大蟲真傳・薛永","cooldown":5,"mechanic":"dizha_48_quake_echo","primary":"quake","secondary":"echo","power":0.83,"statusPower":27,"signature":"quake:echo:48","stats":{"speed":5,"crit":0.008,"status":0.03}},
    49:{"hero":"施恩","nickname":"金眼彪","activeName":"金眼彪・破甲穿陣","activeText":"穿透防禦並施加破甲；施術後自身加速。","passiveName":"金眼彪・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"金眼彪真傳・施恩","cooldown":2,"mechanic":"dizha_49_pierce_swift","primary":"pierce","secondary":"swift","power":0.885,"statusPower":30,"signature":"pierce:swift:49","stats":{"speed":0,"crit":0.016,"status":0.0}},
    50:{"hero":"李立","nickname":"催命判官","activeName":"催命判官・破甲穿陣","activeText":"穿透防禦並施加破甲；保護氣血最低隊友。","passiveName":"催命判官・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"催命判官真傳・李立","cooldown":3,"mechanic":"dizha_50_pierce_guard","primary":"pierce","secondary":"guard","power":0.94,"statusPower":33,"signature":"pierce:guard:50","stats":{"speed":1,"crit":0.024,"status":0.01}},
    51:{"hero":"李俊","nickname":"混江龍","activeName":"混江龍・破甲穿陣","activeText":"穿透防禦並施加破甲；提高下一擊暴擊與命中。","passiveName":"混江龍・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"混江龍真傳・李俊","cooldown":4,"mechanic":"dizha_51_pierce_insight","primary":"pierce","secondary":"insight","power":0.995,"statusPower":36,"signature":"pierce:insight:51","stats":{"speed":2,"crit":0.032,"status":0.02}},
    52:{"hero":"童威","nickname":"出洞蛟","activeName":"出洞蛟・破甲穿陣","activeText":"穿透防禦並施加破甲；擊倒敵人時取得少量銀兩。","passiveName":"出洞蛟・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"出洞蛟真傳・童威","cooldown":5,"mechanic":"dizha_52_pierce_harvest","primary":"pierce","secondary":"harvest","power":1.05,"statusPower":39,"signature":"pierce:harvest:52","stats":{"speed":3,"crit":0.0,"status":0.03}},
    53:{"hero":"童猛","nickname":"翻江蜃","activeName":"翻江蜃・破甲穿陣","activeText":"穿透防禦並施加破甲；清除自身一項負面狀態。","passiveName":"翻江蜃・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"翻江蜃真傳・童猛","cooldown":2,"mechanic":"dizha_53_pierce_cleanse","primary":"pierce","secondary":"cleanse","power":1.105,"statusPower":18,"signature":"pierce:cleanse:53","stats":{"speed":4,"crit":0.008,"status":0.0}},
    54:{"hero":"阮小二","nickname":"立地太歲","activeName":"立地太歲・破甲穿陣","activeText":"穿透防禦並施加破甲；有機率縮短技能冷卻。","passiveName":"立地太歲・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"立地太歲真傳・阮小二","cooldown":3,"mechanic":"dizha_54_pierce_echo","primary":"pierce","secondary":"echo","power":1.16,"statusPower":21,"signature":"pierce:echo:54","stats":{"speed":5,"crit":0.016,"status":0.01}},
    55:{"hero":"張橫","nickname":"船火兒","activeName":"船火兒・濟眾回春","activeText":"治療全隊並解除一項持續傷害；施術後自身加速。","passiveName":"船火兒・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"船火兒真傳・張橫","cooldown":4,"mechanic":"dizha_55_heal_swift","primary":"heal","secondary":"swift","power":0.72,"statusPower":24,"signature":"heal:swift:55","stats":{"speed":0,"crit":0.024,"status":0.02}},
    56:{"hero":"阮小五","nickname":"短命二郎","activeName":"短命二郎・濟眾回春","activeText":"治療全隊並解除一項持續傷害；保護氣血最低隊友。","passiveName":"短命二郎・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"短命二郎真傳・阮小五","cooldown":5,"mechanic":"dizha_56_heal_guard","primary":"heal","secondary":"guard","power":0.775,"statusPower":27,"signature":"heal:guard:56","stats":{"speed":1,"crit":0.032,"status":0.03}},
    57:{"hero":"阮小七","nickname":"活閻羅","activeName":"活閻羅・濟眾回春","activeText":"治療全隊並解除一項持續傷害；提高下一擊暴擊與命中。","passiveName":"活閻羅・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"活閻羅真傳・阮小七","cooldown":2,"mechanic":"dizha_57_heal_insight","primary":"heal","secondary":"insight","power":0.83,"statusPower":30,"signature":"heal:insight:57","stats":{"speed":2,"crit":0.0,"status":0.0}},
    58:{"hero":"楊雄","nickname":"病關索","activeName":"病關索・濟眾回春","activeText":"治療全隊並解除一項持續傷害；擊倒敵人時取得少量銀兩。","passiveName":"病關索・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"病關索真傳・楊雄","cooldown":3,"mechanic":"dizha_58_heal_harvest","primary":"heal","secondary":"harvest","power":0.885,"statusPower":33,"signature":"heal:harvest:58","stats":{"speed":3,"crit":0.008,"status":0.01}},
    59:{"hero":"石秀","nickname":"拼命三郎","activeName":"拼命三郎・濟眾回春","activeText":"治療全隊並解除一項持續傷害；清除自身一項負面狀態。","passiveName":"拼命三郎・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"拼命三郎真傳・石秀","cooldown":4,"mechanic":"dizha_59_heal_cleanse","primary":"heal","secondary":"cleanse","power":0.94,"statusPower":36,"signature":"heal:cleanse:59","stats":{"speed":4,"crit":0.016,"status":0.02}},
    60:{"hero":"柴進","nickname":"小旋風","activeName":"小旋風・濟眾回春","activeText":"治療全隊並解除一項持續傷害；有機率縮短技能冷卻。","passiveName":"小旋風・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"小旋風真傳・柴進","cooldown":5,"mechanic":"dizha_60_heal_echo","primary":"heal","secondary":"echo","power":0.995,"statusPower":39,"signature":"heal:echo:60","stats":{"speed":5,"crit":0.024,"status":0.03}},
    61:{"hero":"關勝","nickname":"大刀","activeName":"大刀・神行調序","activeText":"提高全隊速度並推進最慢隊友；施術後自身加速。","passiveName":"大刀・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"大刀真傳・關勝","cooldown":2,"mechanic":"dizha_61_haste_swift","primary":"haste","secondary":"swift","power":1.05,"statusPower":18,"signature":"haste:swift:61","stats":{"speed":0,"crit":0.032,"status":0.0}},
    62:{"hero":"秦明","nickname":"霹靂火","activeName":"霹靂火・神行調序","activeText":"提高全隊速度並推進最慢隊友；保護氣血最低隊友。","passiveName":"霹靂火・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"霹靂火真傳・秦明","cooldown":3,"mechanic":"dizha_62_haste_guard","primary":"haste","secondary":"guard","power":1.105,"statusPower":21,"signature":"haste:guard:62","stats":{"speed":1,"crit":0.0,"status":0.01}},
    63:{"hero":"董平","nickname":"雙槍將","activeName":"雙槍將・神行調序","activeText":"提高全隊速度並推進最慢隊友；提高下一擊暴擊與命中。","passiveName":"雙槍將・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"雙槍將真傳・董平","cooldown":4,"mechanic":"dizha_63_haste_insight","primary":"haste","secondary":"insight","power":1.16,"statusPower":24,"signature":"haste:insight:63","stats":{"speed":2,"crit":0.008,"status":0.02}},
    64:{"hero":"徐寧","nickname":"金槍手","activeName":"金槍手・神行調序","activeText":"提高全隊速度並推進最慢隊友；擊倒敵人時取得少量銀兩。","passiveName":"金槍手・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"金槍手真傳・徐寧","cooldown":5,"mechanic":"dizha_64_haste_harvest","primary":"haste","secondary":"harvest","power":0.72,"statusPower":27,"signature":"haste:harvest:64","stats":{"speed":3,"crit":0.016,"status":0.03}},
    65:{"hero":"索超","nickname":"急先鋒","activeName":"急先鋒・神行調序","activeText":"提高全隊速度並推進最慢隊友；清除自身一項負面狀態。","passiveName":"急先鋒・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"急先鋒真傳・索超","cooldown":2,"mechanic":"dizha_65_haste_cleanse","primary":"haste","secondary":"cleanse","power":0.775,"statusPower":30,"signature":"haste:cleanse:65","stats":{"speed":4,"crit":0.024,"status":0.0}},
    66:{"hero":"劉唐","nickname":"赤髮鬼","activeName":"赤髮鬼・神行調序","activeText":"提高全隊速度並推進最慢隊友；有機率縮短技能冷卻。","passiveName":"赤髮鬼・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"赤髮鬼真傳・劉唐","cooldown":3,"mechanic":"dizha_66_haste_echo","primary":"haste","secondary":"echo","power":0.83,"statusPower":33,"signature":"haste:echo:66","stats":{"speed":5,"crit":0.032,"status":0.01}},
    67:{"hero":"史進","nickname":"九紋龍","activeName":"九紋龍・奇毒蔓延","activeText":"施加中毒，擊倒時向其他敵人擴散；施術後自身加速。","passiveName":"九紋龍・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"九紋龍真傳・史進","cooldown":4,"mechanic":"dizha_67_poison_swift","primary":"poison","secondary":"swift","power":0.885,"statusPower":36,"signature":"poison:swift:67","stats":{"speed":0,"crit":0.0,"status":0.02}},
    68:{"hero":"黃信","nickname":"鎮三山","activeName":"鎮三山・奇毒蔓延","activeText":"施加中毒，擊倒時向其他敵人擴散；保護氣血最低隊友。","passiveName":"鎮三山・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"鎮三山真傳・黃信","cooldown":5,"mechanic":"dizha_68_poison_guard","primary":"poison","secondary":"guard","power":0.94,"statusPower":39,"signature":"poison:guard:68","stats":{"speed":1,"crit":0.008,"status":0.03}},
    69:{"hero":"孫立","nickname":"病尉遲","activeName":"病尉遲・奇毒蔓延","activeText":"施加中毒，擊倒時向其他敵人擴散；提高下一擊暴擊與命中。","passiveName":"病尉遲・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"病尉遲真傳・孫立","cooldown":2,"mechanic":"dizha_69_poison_insight","primary":"poison","secondary":"insight","power":0.995,"statusPower":18,"signature":"poison:insight:69","stats":{"speed":2,"crit":0.016,"status":0.0}},
    70:{"hero":"宣贊","nickname":"醜郡馬","activeName":"醜郡馬・奇毒蔓延","activeText":"施加中毒，擊倒時向其他敵人擴散；擊倒敵人時取得少量銀兩。","passiveName":"醜郡馬・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"醜郡馬真傳・宣贊","cooldown":3,"mechanic":"dizha_70_poison_harvest","primary":"poison","secondary":"harvest","power":1.05,"statusPower":21,"signature":"poison:harvest:70","stats":{"speed":3,"crit":0.024,"status":0.01}},
    71:{"hero":"郝思文","nickname":"井木犴","activeName":"井木犴・奇毒蔓延","activeText":"施加中毒，擊倒時向其他敵人擴散；清除自身一項負面狀態。","passiveName":"井木犴・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"井木犴真傳・郝思文","cooldown":4,"mechanic":"dizha_71_poison_cleanse","primary":"poison","secondary":"cleanse","power":1.105,"statusPower":24,"signature":"poison:cleanse:71","stats":{"speed":4,"crit":0.032,"status":0.02}},
    72:{"hero":"韓滔","nickname":"百勝將","activeName":"百勝將・奇毒蔓延","activeText":"施加中毒，擊倒時向其他敵人擴散；有機率縮短技能冷卻。","passiveName":"百勝將・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"百勝將真傳・韓滔","cooldown":5,"mechanic":"dizha_72_poison_echo","primary":"poison","secondary":"echo","power":1.16,"statusPower":27,"signature":"poison:echo:72","stats":{"speed":5,"crit":0.0,"status":0.03}},
    73:{"hero":"彭玘","nickname":"天目將","activeName":"天目將・裂創追斬","activeText":"施加流血並對負面狀態目標增傷；施術後自身加速。","passiveName":"天目將・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"天目將真傳・彭玘","cooldown":2,"mechanic":"dizha_73_bleed_swift","primary":"bleed","secondary":"swift","power":0.72,"statusPower":30,"signature":"bleed:swift:73","stats":{"speed":0,"crit":0.008,"status":0.0}},
    74:{"hero":"單廷珪","nickname":"聖水將","activeName":"聖水將・裂創追斬","activeText":"施加流血並對負面狀態目標增傷；保護氣血最低隊友。","passiveName":"聖水將・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"聖水將真傳・單廷珪","cooldown":3,"mechanic":"dizha_74_bleed_guard","primary":"bleed","secondary":"guard","power":0.775,"statusPower":33,"signature":"bleed:guard:74","stats":{"speed":1,"crit":0.016,"status":0.01}},
    75:{"hero":"魏定國","nickname":"神火將","activeName":"神火將・裂創追斬","activeText":"施加流血並對負面狀態目標增傷；提高下一擊暴擊與命中。","passiveName":"神火將・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"神火將真傳・魏定國","cooldown":4,"mechanic":"dizha_75_bleed_insight","primary":"bleed","secondary":"insight","power":0.83,"statusPower":36,"signature":"bleed:insight:75","stats":{"speed":2,"crit":0.024,"status":0.02}},
    76:{"hero":"歐鵬","nickname":"摩雲金翅","activeName":"摩雲金翅・裂創追斬","activeText":"施加流血並對負面狀態目標增傷；擊倒敵人時取得少量銀兩。","passiveName":"摩雲金翅・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"摩雲金翅真傳・歐鵬","cooldown":5,"mechanic":"dizha_76_bleed_harvest","primary":"bleed","secondary":"harvest","power":0.885,"statusPower":39,"signature":"bleed:harvest:76","stats":{"speed":3,"crit":0.032,"status":0.03}},
    77:{"hero":"鄧飛","nickname":"火眼狻猊","activeName":"火眼狻猊・裂創追斬","activeText":"施加流血並對負面狀態目標增傷；清除自身一項負面狀態。","passiveName":"火眼狻猊・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"火眼狻猊真傳・鄧飛","cooldown":2,"mechanic":"dizha_77_bleed_cleanse","primary":"bleed","secondary":"cleanse","power":0.94,"statusPower":18,"signature":"bleed:cleanse:77","stats":{"speed":4,"crit":0.0,"status":0.0}},
    78:{"hero":"燕順","nickname":"錦毛虎","activeName":"錦毛虎・裂創追斬","activeText":"施加流血並對負面狀態目標增傷；有機率縮短技能冷卻。","passiveName":"錦毛虎・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"錦毛虎真傳・燕順","cooldown":3,"mechanic":"dizha_78_bleed_echo","primary":"bleed","secondary":"echo","power":0.995,"statusPower":21,"signature":"bleed:echo:78","stats":{"speed":5,"crit":0.008,"status":0.01}},
    79:{"hero":"楊林","nickname":"錦豹子","activeName":"錦豹子・定身封招","activeText":"施加遲緩、沉默或暈眩；施術後自身加速。","passiveName":"錦豹子・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"錦豹子真傳・楊林","cooldown":4,"mechanic":"dizha_79_control_swift","primary":"control","secondary":"swift","power":1.05,"statusPower":24,"signature":"control:swift:79","stats":{"speed":0,"crit":0.016,"status":0.02}},
    80:{"hero":"蔣敬","nickname":"神算子","activeName":"神算子・定身封招","activeText":"施加遲緩、沉默或暈眩；保護氣血最低隊友。","passiveName":"神算子・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"神算子真傳・蔣敬","cooldown":5,"mechanic":"dizha_80_control_guard","primary":"control","secondary":"guard","power":1.105,"statusPower":27,"signature":"control:guard:80","stats":{"speed":1,"crit":0.024,"status":0.03}},
    81:{"hero":"呂方","nickname":"小溫侯","activeName":"小溫侯・定身封招","activeText":"施加遲緩、沉默或暈眩；提高下一擊暴擊與命中。","passiveName":"小溫侯・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"小溫侯真傳・呂方","cooldown":2,"mechanic":"dizha_81_control_insight","primary":"control","secondary":"insight","power":1.16,"statusPower":30,"signature":"control:insight:81","stats":{"speed":2,"crit":0.032,"status":0.0}},
    82:{"hero":"郭盛","nickname":"賽仁貴","activeName":"賽仁貴・定身封招","activeText":"施加遲緩、沉默或暈眩；擊倒敵人時取得少量銀兩。","passiveName":"賽仁貴・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"賽仁貴真傳・郭盛","cooldown":3,"mechanic":"dizha_82_control_harvest","primary":"control","secondary":"harvest","power":0.72,"statusPower":33,"signature":"control:harvest:82","stats":{"speed":3,"crit":0.0,"status":0.01}},
    83:{"hero":"安道全","nickname":"神醫","activeName":"神醫・定身封招","activeText":"施加遲緩、沉默或暈眩；清除自身一項負面狀態。","passiveName":"神醫・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"神醫真傳・安道全","cooldown":4,"mechanic":"dizha_83_control_cleanse","primary":"control","secondary":"cleanse","power":0.775,"statusPower":36,"signature":"control:cleanse:83","stats":{"speed":4,"crit":0.008,"status":0.02}},
    84:{"hero":"王英","nickname":"矮腳虎","activeName":"矮腳虎・定身封招","activeText":"施加遲緩、沉默或暈眩；有機率縮短技能冷卻。","passiveName":"矮腳虎・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"矮腳虎真傳・王英","cooldown":5,"mechanic":"dizha_84_control_echo","primary":"control","secondary":"echo","power":0.83,"statusPower":39,"signature":"control:echo:84","stats":{"speed":5,"crit":0.016,"status":0.03}},
    85:{"hero":"鮑旭","nickname":"喪門神","activeName":"喪門神・鐵壁反守","activeText":"建立護盾並賦予反擊；施術後自身加速。","passiveName":"喪門神・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"喪門神真傳・鮑旭","cooldown":2,"mechanic":"dizha_85_shield_swift","primary":"shield","secondary":"swift","power":0.885,"statusPower":18,"signature":"shield:swift:85","stats":{"speed":0,"crit":0.024,"status":0.0}},
    86:{"hero":"樊瑞","nickname":"混世魔王","activeName":"混世魔王・鐵壁反守","activeText":"建立護盾並賦予反擊；保護氣血最低隊友。","passiveName":"混世魔王・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"混世魔王真傳・樊瑞","cooldown":3,"mechanic":"dizha_86_shield_guard","primary":"shield","secondary":"guard","power":0.94,"statusPower":21,"signature":"shield:guard:86","stats":{"speed":1,"crit":0.032,"status":0.01}},
    87:{"hero":"孔明","nickname":"毛頭星","activeName":"毛頭星・鐵壁反守","activeText":"建立護盾並賦予反擊；提高下一擊暴擊與命中。","passiveName":"毛頭星・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"毛頭星真傳・孔明","cooldown":4,"mechanic":"dizha_87_shield_insight","primary":"shield","secondary":"insight","power":0.995,"statusPower":24,"signature":"shield:insight:87","stats":{"speed":2,"crit":0.0,"status":0.02}},
    88:{"hero":"孔亮","nickname":"獨火星","activeName":"獨火星・鐵壁反守","activeText":"建立護盾並賦予反擊；擊倒敵人時取得少量銀兩。","passiveName":"獨火星・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"獨火星真傳・孔亮","cooldown":5,"mechanic":"dizha_88_shield_harvest","primary":"shield","secondary":"harvest","power":1.05,"statusPower":27,"signature":"shield:harvest:88","stats":{"speed":3,"crit":0.008,"status":0.03}},
    89:{"hero":"項充","nickname":"八臂哪吒","activeName":"八臂哪吒・鐵壁反守","activeText":"建立護盾並賦予反擊；清除自身一項負面狀態。","passiveName":"八臂哪吒・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"八臂哪吒真傳・項充","cooldown":2,"mechanic":"dizha_89_shield_cleanse","primary":"shield","secondary":"cleanse","power":1.105,"statusPower":30,"signature":"shield:cleanse:89","stats":{"speed":4,"crit":0.016,"status":0.0}},
    90:{"hero":"李袞","nickname":"飛天大聖","activeName":"飛天大聖・鐵壁反守","activeText":"建立護盾並賦予反擊；有機率縮短技能冷卻。","passiveName":"飛天大聖・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"飛天大聖真傳・李袞","cooldown":3,"mechanic":"dizha_90_shield_echo","primary":"shield","secondary":"echo","power":1.16,"statusPower":33,"signature":"shield:echo:90","stats":{"speed":5,"crit":0.024,"status":0.01}},
    91:{"hero":"馬麟","nickname":"鐵笛仙","activeName":"鐵笛仙・斷命制勝","activeText":"對低氣血敵人造成處決傷害；施術後自身加速。","passiveName":"鐵笛仙・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"鐵笛仙真傳・馬麟","cooldown":4,"mechanic":"dizha_91_execute_swift","primary":"execute","secondary":"swift","power":0.72,"statusPower":36,"signature":"execute:swift:91","stats":{"speed":0,"crit":0.032,"status":0.02}},
    92:{"hero":"陳達","nickname":"跳澗虎","activeName":"跳澗虎・斷命制勝","activeText":"對低氣血敵人造成處決傷害；保護氣血最低隊友。","passiveName":"跳澗虎・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"跳澗虎真傳・陳達","cooldown":5,"mechanic":"dizha_92_execute_guard","primary":"execute","secondary":"guard","power":0.775,"statusPower":39,"signature":"execute:guard:92","stats":{"speed":1,"crit":0.0,"status":0.03}},
    93:{"hero":"楊春","nickname":"白花蛇","activeName":"白花蛇・斷命制勝","activeText":"對低氣血敵人造成處決傷害；提高下一擊暴擊與命中。","passiveName":"白花蛇・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"白花蛇真傳・楊春","cooldown":2,"mechanic":"dizha_93_execute_insight","primary":"execute","secondary":"insight","power":0.83,"statusPower":18,"signature":"execute:insight:93","stats":{"speed":2,"crit":0.008,"status":0.0}},
    94:{"hero":"鄭天壽","nickname":"白面郎君","activeName":"白面郎君・斷命制勝","activeText":"對低氣血敵人造成處決傷害；擊倒敵人時取得少量銀兩。","passiveName":"白面郎君・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"白面郎君真傳・鄭天壽","cooldown":3,"mechanic":"dizha_94_execute_harvest","primary":"execute","secondary":"harvest","power":0.885,"statusPower":21,"signature":"execute:harvest:94","stats":{"speed":3,"crit":0.016,"status":0.01}},
    95:{"hero":"宋清","nickname":"鐵扇子","activeName":"鐵扇子・斷命制勝","activeText":"對低氣血敵人造成處決傷害；清除自身一項負面狀態。","passiveName":"鐵扇子・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"鐵扇子真傳・宋清","cooldown":4,"mechanic":"dizha_95_execute_cleanse","primary":"execute","secondary":"cleanse","power":0.94,"statusPower":24,"signature":"execute:cleanse:95","stats":{"speed":4,"crit":0.024,"status":0.02}},
    96:{"hero":"龔旺","nickname":"花項虎","activeName":"花項虎・斷命制勝","activeText":"對低氣血敵人造成處決傷害；有機率縮短技能冷卻。","passiveName":"花項虎・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"花項虎真傳・龔旺","cooldown":5,"mechanic":"dizha_96_execute_echo","primary":"execute","secondary":"echo","power":0.995,"statusPower":27,"signature":"execute:echo:96","stats":{"speed":5,"crit":0.032,"status":0.03}},
    97:{"hero":"丁得孫","nickname":"中箭虎","activeName":"中箭虎・聚義回氣","activeText":"回復豪氣與合擊值並支援隊友；施術後自身加速。","passiveName":"中箭虎・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"中箭虎真傳・丁得孫","cooldown":2,"mechanic":"dizha_97_resource_swift","primary":"resource","secondary":"swift","power":1.05,"statusPower":30,"signature":"resource:swift:97","stats":{"speed":0,"crit":0.0,"status":0.0}},
    98:{"hero":"李忠","nickname":"打虎將","activeName":"打虎將・聚義回氣","activeText":"回復豪氣與合擊值並支援隊友；保護氣血最低隊友。","passiveName":"打虎將・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"打虎將真傳・李忠","cooldown":3,"mechanic":"dizha_98_resource_guard","primary":"resource","secondary":"guard","power":1.105,"statusPower":33,"signature":"resource:guard:98","stats":{"speed":1,"crit":0.008,"status":0.01}},
    99:{"hero":"周通","nickname":"小霸王","activeName":"小霸王・聚義回氣","activeText":"回復豪氣與合擊值並支援隊友；提高下一擊暴擊與命中。","passiveName":"小霸王・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"小霸王真傳・周通","cooldown":4,"mechanic":"dizha_99_resource_insight","primary":"resource","secondary":"insight","power":1.16,"statusPower":36,"signature":"resource:insight:99","stats":{"speed":2,"crit":0.016,"status":0.02}},
    100:{"hero":"蔡福","nickname":"鐵臂膊","activeName":"鐵臂膊・聚義回氣","activeText":"回復豪氣與合擊值並支援隊友；擊倒敵人時取得少量銀兩。","passiveName":"鐵臂膊・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"鐵臂膊真傳・蔡福","cooldown":5,"mechanic":"dizha_100_resource_harvest","primary":"resource","secondary":"harvest","power":0.72,"statusPower":39,"signature":"resource:harvest:100","stats":{"speed":3,"crit":0.024,"status":0.03}},
    101:{"hero":"蔡慶","nickname":"一枝花","activeName":"一枝花・聚義回氣","activeText":"回復豪氣與合擊值並支援隊友；清除自身一項負面狀態。","passiveName":"一枝花・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"一枝花真傳・蔡慶","cooldown":2,"mechanic":"dizha_101_resource_cleanse","primary":"resource","secondary":"cleanse","power":0.775,"statusPower":18,"signature":"resource:cleanse:101","stats":{"speed":4,"crit":0.032,"status":0.0}},
    102:{"hero":"焦挺","nickname":"沒面目","activeName":"沒面目・聚義回氣","activeText":"回復豪氣與合擊值並支援隊友；有機率縮短技能冷卻。","passiveName":"沒面目・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"沒面目真傳・焦挺","cooldown":3,"mechanic":"dizha_102_resource_echo","primary":"resource","secondary":"echo","power":0.83,"statusPower":21,"signature":"resource:echo:102","stats":{"speed":5,"crit":0.0,"status":0.01}},
    103:{"hero":"石勇","nickname":"石將軍","activeName":"石將軍・援軍協戰","activeText":"召來援手造成範圍傷害與鼓舞；施術後自身加速。","passiveName":"石將軍・疾風餘勢","passiveText":"施術後自身加速，並依英雄等級提高效果。","awakeningName":"石將軍真傳・石勇","cooldown":4,"mechanic":"dizha_103_summon_swift","primary":"summon","secondary":"swift","power":0.885,"statusPower":24,"signature":"summon:swift:103","stats":{"speed":0,"crit":0.008,"status":0.02}},
    104:{"hero":"王定六","nickname":"活閃婆","activeName":"活閃婆・援軍協戰","activeText":"召來援手造成範圍傷害與鼓舞；保護氣血最低隊友。","passiveName":"活閃婆・護友之志","passiveText":"保護氣血最低隊友，並依英雄等級提高效果。","awakeningName":"活閃婆真傳・王定六","cooldown":5,"mechanic":"dizha_104_summon_guard","primary":"summon","secondary":"guard","power":0.94,"statusPower":27,"signature":"summon:guard:104","stats":{"speed":1,"crit":0.016,"status":0.03}},
    105:{"hero":"郁保四","nickname":"險道神","activeName":"險道神・援軍協戰","activeText":"召來援手造成範圍傷害與鼓舞；提高下一擊暴擊與命中。","passiveName":"險道神・洞察破綻","passiveText":"提高下一擊暴擊與命中，並依英雄等級提高效果。","awakeningName":"險道神真傳・郁保四","cooldown":2,"mechanic":"dizha_105_summon_insight","primary":"summon","secondary":"insight","power":0.995,"statusPower":30,"signature":"summon:insight:105","stats":{"speed":2,"crit":0.024,"status":0.0}},
    106:{"hero":"白勝","nickname":"白日鼠","activeName":"白日鼠・援軍協戰","activeText":"召來援手造成範圍傷害與鼓舞；擊倒敵人時取得少量銀兩。","passiveName":"白日鼠・善後得資","passiveText":"擊倒敵人時取得少量銀兩，並依英雄等級提高效果。","awakeningName":"白日鼠真傳・白勝","cooldown":3,"mechanic":"dizha_106_summon_harvest","primary":"summon","secondary":"harvest","power":1.05,"statusPower":33,"signature":"summon:harvest:106","stats":{"speed":3,"crit":0.032,"status":0.01}},
    107:{"hero":"時遷","nickname":"鼓上蚤","activeName":"鼓上蚤・援軍協戰","activeText":"召來援手造成範圍傷害與鼓舞；清除自身一項負面狀態。","passiveName":"鼓上蚤・清心定志","passiveText":"清除自身一項負面狀態，並依英雄等級提高效果。","awakeningName":"鼓上蚤真傳・時遷","cooldown":4,"mechanic":"dizha_107_summon_cleanse","primary":"summon","secondary":"cleanse","power":1.105,"statusPower":36,"signature":"summon:cleanse:107","stats":{"speed":4,"crit":0.0,"status":0.02}},
    108:{"hero":"段景住","nickname":"金毛犬","activeName":"金毛犬・援軍協戰","activeText":"召來援手造成範圍傷害與鼓舞；有機率縮短技能冷卻。","passiveName":"金毛犬・餘韻再發","passiveText":"有機率縮短技能冷卻，並依英雄等級提高效果。","awakeningName":"金毛犬真傳・段景住","cooldown":5,"mechanic":"dizha_108_summon_echo","primary":"summon","secondary":"echo","power":1.16,"statusPower":39,"signature":"summon:echo:108","stats":{"speed":5,"crit":0.008,"status":0.03}}
  };


  const get = number => records[Number(number)] || null;
  function execute(number,c){
    const r=get(number); if(!r||!c)return '';
    const a=c.actor,t=c.target;
    const enemies=()=>c.enemies().filter(x=>x.alive);
    const allies=()=>c.allies().filter(x=>x.alive);
    const low=()=>allies().sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];
    const hit=(target,mult,opts={})=>c.hit(target,mult,opts);
    let total=0,note='';
    switch(r.primary){
      case 'chain': for(let i=0;i<3&&t.alive;i++)total+=hit(t,r.power*(.52+i*.1),{crit:i===2}); if(!t.alive){const x=enemies().sort((x,y)=>x.hp-y.hp)[0];if(x)total+=hit(x,r.power*.8,{pierce:true});} note=`連環追擊 ${total}`;break;
      case 'quake': enemies().forEach(e=>total+=hit(e,r.power*.72));allies().forEach(x=>c.shield(x,55+a.level*4));note=`震陣 ${total}，全隊護盾`;break;
      case 'pierce': total=hit(t,r.power*1.35,{pierce:true});c.status(t,'armorBreak',3,r.statusPower);note=`穿陣 ${total}，破甲`;break;
      case 'heal': allies().forEach(x=>c.heal(x,a.atk*(.36+r.power*.22)));for(const x of allies()){for(const k of ['poison','burn','bleed'])if(x.statuses?.[k]){delete x.statuses[k];break;}}note='濟眾回春並清除持續傷害';break;
      case 'haste': allies().forEach(x=>c.status(x,'haste',2,10+r.statusPower));{const x=[...allies()].sort((x,y)=>x.speed-y.speed)[0];if(x)c.requeue(x.id,850);}note='神行調序，全隊加速';break;
      case 'poison': total=hit(t,r.power*.9,{pierce:true});c.status(t,'poison',4,r.statusPower+a.level);note=`奇毒 ${total}，附加中毒`;break;
      case 'bleed': total=hit(t,r.power*(t.statuses&&Object.keys(t.statuses).length?1.35:1.05));c.status(t,'bleed',4,r.statusPower+a.level);note=`裂創 ${total}，附加流血`;break;
      case 'control': total=hit(t,r.power*.82);{const effects=['slow','silence','stun'];const k=effects[number%3];c.status(t,k,k==='stun'?1:2,k==='stun'?1:r.statusPower);}note=`封招 ${total}`;break;
      case 'shield': total=hit(t,r.power*.7);c.shield(a,90+a.level*5);c.status(a,'counter',2,.55+r.power*.12);note=`反守 ${total}，護盾與反擊`;break;
      case 'execute': {const m=t.hp/t.maxHp<.45?1.85:1.05;total=hit(t,r.power*m,{crit:t.hp/t.maxHp<.45,pierce:true});note=`斷命 ${total}`;}break;
      case 'resource': c.teamSp(28+number%18);c.combo(22+number%25);{const x=low();if(x)c.heal(x,a.atk*.42);}note='聚義回氣並支援弱者';break;
      case 'summon': enemies().forEach(e=>total+=hit(e,r.power*.64));allies().forEach(x=>c.status(x,'power',2,12+number%12));note=`援軍協戰 ${total}，全隊鼓舞`;break;
      default: total=hit(t,1.1);note=`真傳一擊 ${total}`;
    }
    switch(r.secondary){
      case 'swift': c.status(a,'haste',2,12+number%10);note+='，疾風加速';break;
      case 'guard': {const x=low();if(x){c.shield(x,50+a.level*3);c.status(x,'guarded',2,.2);note+=`，護衛${x.name}`;}}break;
      case 'insight': c.status(a,'precision',2,18);c.status(a,'power',1,10);note+='，洞察破綻';break;
      case 'harvest': if(!t.alive){const gain=12+number%18;c.addSilver?.(gain);note+=`，善後得銀 ${gain}`;}break;
      case 'cleanse': for(const k of ['poison','burn','bleed','slow','weaken','armorBreak','silence'])if(a.statuses?.[k]){delete a.statuses[k];note+=`，清除${k}`;break;}break;
      case 'echo': if(c.random()<.20+(number%5)*.02){a.cooldowns.skill=Math.max(0,(a.cooldowns.skill||0)-2);note+='，餘韻縮短冷卻';}break;
    }
    return note;
  }
  window.LS75Dizha={records,get,execute,count:Object.keys(records).length,signatures:Object.values(records).map(x=>x.signature)};
})();
