const CACHE = 'liangshan-v7.6.0-cache-1';
const ASSETS = ["./", "./index.html", "./styles.css", "./chapters.js", "./game.js", "./manifest.webmanifest", "./modules/tiangang.js", "./modules/dizha.js", "./modules/save-schema.js", "./modules/cloud-sync.js", "./modules/endgame.js", "./modules/content-v74.js", "./modules/epic-chapters.js", "./modules/epic-chapters-v76.js", "./modules/roguelike.js", "./modules/roguelike-v76.js", "./modules/telemetry.js", "./modules/balance-v76.js", "./modules/operations-v76.js", "./modules/audio-v76.js", "./modules/accessibility.js", "./assets/icon-192.png", "./assets/icon-512.png", "./README.md", "./FIREBASE_SETUP.md", "./DEPLOY_GITHUB_PAGES.md", "./LIVE_DEPLOYMENT_CHECKLIST.md", "./SCREEN_READER_CHECKLIST.md", "./assets/portraits/hero-001.svg", "./assets/portraits/hero-002.svg", "./assets/portraits/hero-003.svg", "./assets/portraits/hero-004.svg", "./assets/portraits/hero-005.svg", "./assets/portraits/hero-006.svg", "./assets/portraits/hero-007.svg", "./assets/portraits/hero-008.svg", "./assets/portraits/hero-009.svg", "./assets/portraits/hero-010.svg", "./assets/portraits/hero-011.svg", "./assets/portraits/hero-012.svg", "./assets/portraits/hero-013.svg", "./assets/portraits/hero-014.svg", "./assets/portraits/hero-015.svg", "./assets/portraits/hero-016.svg", "./assets/portraits/hero-017.svg", "./assets/portraits/hero-018.svg", "./assets/portraits/hero-019.svg", "./assets/portraits/hero-020.svg", "./assets/portraits/hero-021.svg", "./assets/portraits/hero-022.svg", "./assets/portraits/hero-023.svg", "./assets/portraits/hero-024.svg", "./assets/portraits/hero-025.svg", "./assets/portraits/hero-026.svg", "./assets/portraits/hero-027.svg", "./assets/portraits/hero-028.svg", "./assets/portraits/hero-029.svg", "./assets/portraits/hero-030.svg", "./assets/portraits/hero-031.svg", "./assets/portraits/hero-032.svg", "./assets/portraits/hero-033.svg", "./assets/portraits/hero-034.svg", "./assets/portraits/hero-035.svg", "./assets/portraits/hero-036.svg", "./assets/backgrounds/scene-01.svg", "./assets/backgrounds/scene-02.svg", "./assets/backgrounds/scene-03.svg", "./assets/backgrounds/scene-04.svg", "./assets/backgrounds/scene-05.svg", "./assets/backgrounds/scene-06.svg", "./assets/backgrounds/scene-07.svg", "./assets/backgrounds/scene-08.svg", "./assets/backgrounds/scene-09.svg", "./assets/backgrounds/scene-10.svg", "./assets/backgrounds/scene-11.svg", "./assets/backgrounds/scene-12.svg"];
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(caches.match(event.request).then(cached => cached || fetch(event.request).then(response => {
    if(response && response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));}
    return response;
  }).catch(()=>caches.match('./index.html'))));
});
self.addEventListener('message', event => { if(event.data?.type==='SKIP_WAITING') self.skipWaiting(); });
